"""
SIH26 - UNIVERSAL GP BOUNDARY INGESTION ENGINE

Purpose
-------
Collect official Gram Manchitra Gram Panchayat boundaries and build a
downstream-safe GP master without hardcoding state/block-specific fixes.

Design principles
-----------------
1. Raw official GP and Block snapshots are preserved untouched.
2. GP IDs/names are detected dynamically.
3. Repeated GP IDs are NOT blindly dropped.
4. Every source geometry is spatially assessed against the complete
   official Block layer returned by Gram Manchitra.
5. The engine dynamically distinguishes:
      - EXACT_DUPLICATE
      - VALID_MULTIPART
      - CROSS_BLOCK_SOURCE
      - PARTIAL_BLOCK_INTERSECTION
      - NAME_CONFLICT
      - GEOMETRY_INVALID
      - UNRESOLVED
6. No "largest polygon" rule is used.
7. No synthetic geometry is invented.
8. For modelling inside the requested Block, an analysis geometry is
   generated by intersection with the requested Block. The original
   official geometry is preserved separately in source_geometry_wkt.
9. A GP with source geometry extending outside the requested Block is
   not silently discarded; it is retained and flagged.
10. Centroids and areas are calculated in a projected CRS.

The resulting gp_master contains one logical row per GP ID returned by the
official GP query. Source-level provenance and spatial membership are
stored in duplicate_gp_source_audit.csv.
"""

from pathlib import Path
import sys
import json
import hashlib
import warnings
from datetime import datetime, timezone

import pandas as pd
import geopandas as gpd
import requests
from shapely.ops import unary_union
from shapely.geometry import GeometryCollection, Polygon, MultiPolygon

# ---------------------------------------------------------------------
# PATH / IMPORTS
# ---------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = SCRIPT_DIR.parent
PROJECT_ROOT = SCRIPTS_DIR.parent

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from common.geo import (
    clean_name,
    validate_geometry,
    repair_invalid_geometry,
    query_block_gps,
)

# ---------------------------------------------------------------------
# OFFICIAL GRAM MANCHITRA BLOCK LAYER
# ---------------------------------------------------------------------

BLOCK_QUERY_URL = (
    "https://grammanchitragis.nic.in/grammanchitra/rest/services/"
    "panchayat/adminpanch/MapServer/2/query"
)

# Small tolerance only for floating-point comparisons.
AREA_EPSILON_M2 = 1e-6


# ---------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------

def norm(value):
    """Normalize administrative text for comparison only."""
    if value is None:
        return ""
    return (
        str(value)
        .strip()
        .upper()
        .replace("_", " ")
        .replace("-", " ")
    )


def find_column(columns, candidates):
    """Find a field dynamically using exact then relaxed matching."""
    normalized = {
        str(c).strip().lower().replace(" ", "_"): c
        for c in columns
    }

    for candidate in candidates:
        key = candidate.strip().lower().replace(" ", "_")
        if key in normalized:
            return normalized[key]

    for c in columns:
        lc = str(c).strip().lower().replace(" ", "_")
        for candidate in candidates:
            cc = candidate.strip().lower().replace(" ", "_")
            if cc in lc or lc in cc:
                return c

    return None


def geometry_signature(geom):
    """Stable geometry signature for provenance/audit."""
    if geom is None or geom.is_empty:
        return ""

    try:
        return hashlib.sha256(
            geom.normalize().wkb
        ).hexdigest()
    except Exception:
        return hashlib.sha256(
            geom.wkb
        ).hexdigest()


def get_utm_epsg(gdf):
    """Select a local UTM CRS dynamically from the geometry."""
    wgs = gdf.to_crs(4326)

    valid = [
        g for g in wgs.geometry
        if g is not None and not g.is_empty
    ]

    if not valid:
        raise RuntimeError(
            "Cannot determine metric CRS: no valid geometry."
        )

    centroid = unary_union(valid).centroid
    lon = float(centroid.x)
    lat = float(centroid.y)

    zone = int((lon + 180) // 6) + 1
    return 32600 + zone if lat >= 0 else 32700 + zone


def safe_intersection(a, b):
    """Return intersection geometry or None."""
    try:
        if a is None or b is None:
            return None
        if a.is_empty or b.is_empty:
            return None
        return a.intersection(b)
    except Exception:
        return None


def safe_intersection_area(a, b):
    """Return intersection area, or NaN if unavailable."""
    geom = safe_intersection(a, b)
    if geom is None or geom.is_empty:
        return 0.0
    try:
        return float(geom.area)
    except Exception:
        return float("nan")


def polygonal_only(geom):
    """
    Keep only polygonal components from an intersection.

    Boundary-touching lines/points are not useful as GP analysis areas.
    """
    if geom is None or geom.is_empty:
        return None

    if isinstance(geom, Polygon):
        return geom

    if isinstance(geom, MultiPolygon):
        return geom

    if isinstance(geom, GeometryCollection):
        polygons = [
            g for g in geom.geoms
            if isinstance(g, (Polygon, MultiPolygon))
            and not g.is_empty
        ]
        if not polygons:
            return None
        return unary_union(polygons)

    return None


def make_valid_safe(geom):
    """
    Repair geometry conservatively.

    Uses Shapely make_valid when available, otherwise returns original.
    This does not create administrative geometry; it only repairs invalid
    topology.
    """
    if geom is None or geom.is_empty or geom.is_valid:
        return geom

    try:
        from shapely.validation import make_valid
        repaired = make_valid(geom)
        if repaired is not None and not repaired.is_empty:
            return repaired
    except Exception:
        pass

    try:
        repaired = geom.buffer(0)
        if repaired is not None and not repaired.is_empty:
            return repaired
    except Exception:
        pass

    return geom


def choose_block_record(records, state, district, block):
    """Resolve exactly one requested Block from official records."""
    matches = []

    for feature in records:
        props = feature.get("properties", {})

        if (
            norm(props.get("state")) == norm(state)
            and norm(props.get("district")) == norm(district)
            and norm(props.get("block_name")) == norm(block)
        ):
            matches.append(feature)

    if not matches:
        raise RuntimeError(
            f"Could not resolve Block: {state} / {district} / {block}"
        )

    # If the official layer unexpectedly returns multiple records for the
    # same administrative identity, spatially union them rather than
    # choosing one arbitrarily.
    gdf = gpd.GeoDataFrame.from_features(
        matches,
        crs="EPSG:4326",
    )

    return gdf


def fetch_all_block_records(cache_dir=None, force_refresh=False):
    """
    Retrieve the complete official Block layer with a persistent cache.

    The complete Block layer is required by the downstream GP classifier
    because source GP geometries must be checked against *all* official
    Blocks, not only the requested Block.

    Cache behavior:
      1. Reuse a valid local registry when available.
      2. If no cache exists, download the registry once.
      3. Each completed API page is also cached temporarily, so an
         interrupted download can resume instead of starting from zero.
      4. Raw API features are stored unchanged in the final registry.
      5. No synthetic/substitute boundary is created.

    Parameters
    ----------
    cache_dir : Path or str
        Directory used for the official Block registry.
    force_refresh : bool
        If True, ignore the existing registry and download again.
    """
    if cache_dir is None:
        cache_dir = PROJECT_ROOT / "block" / "metadata" / "official_registry"
    else:
        cache_dir = Path(cache_dir)

    cache_dir.mkdir(parents=True, exist_ok=True)

    registry_path = cache_dir / "gram_manchitra_block_registry.geojson"
    metadata_path = cache_dir / "gram_manchitra_block_registry_metadata.json"
    pages_dir = cache_dir / "pages"
    pages_dir.mkdir(parents=True, exist_ok=True)

    def load_geojson_features(path):
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if data.get("type") != "FeatureCollection":
            raise RuntimeError(
                f"Invalid Block registry format: {path}"
            )
        features = data.get("features", [])
        if not features:
            raise RuntimeError(
                f"Block registry contains no features: {path}"
            )
        return features

    # -------------------------------------------------------------
    # Reuse complete registry if it exists.
    # -------------------------------------------------------------
    if registry_path.exists() and not force_refresh:
        try:
            features = load_geojson_features(registry_path)
            print(
                f"  Using cached official Block registry: "
                f"{registry_path}"
            )
            print(
                f"  Cached Block records: {len(features)}"
            )
            return features
        except Exception as exc:
            print(
                "  Existing Block registry could not be loaded; "
                f"refreshing. Reason: {exc}"
            )

    # -------------------------------------------------------------
    # Download pages. Existing completed pages are reused so an
    # interrupted run can resume.
    # -------------------------------------------------------------
    page_size = 1000
    records = []
    offset = 0

    while True:
        page_path = pages_dir / f"block_page_{offset:07d}.geojson"

        if page_path.exists() and not force_refresh:
            try:
                features = load_geojson_features(page_path)
                print(
                    f"  Using cached Block page "
                    f"{offset}-{offset + len(features) - 1}"
                )
            except Exception:
                features = None
        else:
            features = None

        if features is None:
            params = {
                "where": "1=1",
                "outFields": (
                    "block_name,state,district,block_lgd,blkcode11,"
                    "dtcode11,stcode11"
                ),
                "returnGeometry": "true",
                "outSR": "4326",
                "f": "geojson",
                "resultRecordCount": page_size,
                "resultOffset": offset,
            }

            print(
                f"  Downloading official Block page "
                f"starting at offset {offset}..."
            )

            response = requests.get(
                BLOCK_QUERY_URL,
                params=params,
                timeout=(30, 180),
                verify=False,
            )
            response.raise_for_status()

            data = response.json()
            features = data.get("features", [])

            if not features:
                break

            # Write only a fully received page. This allows the next
            # execution to resume from this page if the process stops.
            page_payload = {
                "type": "FeatureCollection",
                "features": features,
            }
            with page_path.open("w", encoding="utf-8") as f:
                json.dump(
                    page_payload,
                    f,
                    ensure_ascii=False,
                )

        if not features:
            break

        records.extend(features)
        print(
            f"  Retrieved block records: {len(records)}"
        )

        if len(features) < page_size:
            break

        offset += page_size

    if not records:
        raise RuntimeError(
            "Official Gram Manchitra Block layer returned no records."
        )

    # -------------------------------------------------------------
    # Persist the complete official registry.
    # -------------------------------------------------------------
    registry_payload = {
        "type": "FeatureCollection",
        "features": records,
    }

    temp_registry = registry_path.with_suffix(".tmp.geojson")
    with temp_registry.open("w", encoding="utf-8") as f:
        json.dump(
            registry_payload,
            f,
            ensure_ascii=False,
        )
    temp_registry.replace(registry_path)

    registry_sha256 = hashlib.sha256(
        registry_path.read_bytes()
    ).hexdigest()

    metadata = {
        "source": "Official Gram Manchitra",
        "source_url": BLOCK_QUERY_URL,
        "retrieved_at_utc": datetime.now(timezone.utc).isoformat(),
        "record_count": len(records),
        "crs": "EPSG:4326",
        "page_size": page_size,
        "registry_sha256": registry_sha256,
        "cache_file": str(registry_path),
        "synthetic_data": False,
    }

    with metadata_path.open("w", encoding="utf-8") as f:
        json.dump(
            metadata,
            f,
            indent=2,
            ensure_ascii=False,
        )

    print(
        f"  Official Block registry cached: {registry_path}"
    )
    print(
        f"  Registry metadata saved: {metadata_path}"
    )

    return records


def build_block_gdf(records):
    """Convert official block records into a GeoDataFrame."""
    return gpd.GeoDataFrame.from_features(
        records,
        crs="EPSG:4326",
    )


def classify_source_parts(
    gp,
    block_all,
    selected_block_gdf,
    gp_id_col,
    gp_name_col,
    metric_epsg,
):
    """
    Dynamically classify every source GP feature.

    Returns:
      source_audit_df
      same_id_relationship_df
      block_membership_df
      cross_gp_overlap_df
      final_master
    """
    gp = gp.copy()
    block_all = block_all.copy()
    selected_block_gdf = selected_block_gdf.copy()

    gp = gp.to_crs(4326)
    block_all = block_all.to_crs(4326)
    selected_block_gdf = selected_block_gdf.to_crs(4326)

    selected_block_geom = unary_union(
        [
            g for g in selected_block_gdf.geometry
            if g is not None and not g.is_empty
        ]
    )

    if selected_block_geom is None or selected_block_geom.is_empty:
        raise RuntimeError(
            "Selected Block geometry is empty."
        )

    gp_m = gp.to_crs(metric_epsg)
    blocks_m = block_all.to_crs(metric_epsg)


    selected_block_m = selected_block_gdf.to_crs(
        metric_epsg
    )
    selected_block_geom_m = unary_union(
        [
            g for g in selected_block_m.geometry
            if g is not None and not g.is_empty
        ]
    )

    # Normalize identifiers only for comparisons.
    gp["_gp_id_norm"] = (
        gp[gp_id_col]
        .astype(str)
        .str.strip()
    )
    gp["_gp_name_norm"] = (
        gp[gp_name_col]
        .astype(str)
        .str.strip()
    )

    # Keep normalized identifiers on BOTH the WGS84 and metric copies.
    # They must be created on gp first, then copied to gp_m.
    gp_m["_gp_id_norm"] = gp["_gp_id_norm"].values
    gp_m["_gp_name_norm"] = gp["_gp_name_norm"].values

    counts = gp["_gp_id_norm"].value_counts()
    duplicate_ids = set(
        counts[counts > 1].index.tolist()
    )

    source_rows = []
    membership_rows = []

    # -------------------------------------------------------------
    # Source-feature -> Block membership
    # -------------------------------------------------------------

    block_sindex = blocks_m.sindex

    for idx in gp_m.index:

        geom = gp_m.loc[idx, "geometry"]
        gp_id = str(gp_m.loc[idx, "_gp_id_norm"])
        gp_name = str(gp_m.loc[idx, "_gp_name_norm"])

        source_area = (
            float(geom.area)
            if geom is not None and not geom.is_empty
            else 0.0
        )

        valid = bool(
            geom is not None
            and not geom.is_empty
            and geom.is_valid
        )

        selected_intersection = safe_intersection(
            geom,
            selected_block_geom_m,
        )

        selected_area = (
            float(selected_intersection.area)
            if selected_intersection is not None
            and not selected_intersection.is_empty
            else 0.0
        )

        selected_pct = (
            100.0 * selected_area / source_area
            if source_area > 0
            else 0.0
        )

        selected_within = bool(
            valid
            and geom.within(selected_block_geom_m)
        )

        selected_intersects = bool(
            selected_area > AREA_EPSILON_M2
        )

        candidate_indices = list(
            block_sindex.query(
                geom,
                predicate="intersects",
            )
        )

        memberships = []

        for bidx in candidate_indices:

            bgeom = blocks_m.loc[
                bidx,
                "geometry",
            ]

            intersection = safe_intersection(
                geom,
                bgeom,
            )

            intersection_area = (
                float(intersection.area)
                if intersection is not None
                and not intersection.is_empty
                else 0.0
            )

            if intersection_area <= AREA_EPSILON_M2:
                continue

            block_name = blocks_m.loc[
                bidx,
                "block_name"
            ] if "block_name" in blocks_m.columns else ""

            state_name = blocks_m.loc[
                bidx,
                "state"
            ] if "state" in blocks_m.columns else ""

            district_name = blocks_m.loc[
                bidx,
                "district"
            ] if "district" in blocks_m.columns else ""

            block_lgd = blocks_m.loc[
                bidx,
                "block_lgd"
            ] if "block_lgd" in blocks_m.columns else ""

            pct = (
                100.0 * intersection_area / source_area
                if source_area > 0
                else 0.0
            )

            memberships.append(
                {
                    "gp_id": gp_id,
                    "source_index": int(idx),
                    "state": str(state_name),
                    "district": str(district_name),
                    "block_name": str(block_name),
                    "block_lgd": str(block_lgd),
                    "intersection_area_km2": (
                        intersection_area / 1_000_000.0
                    ),
                    "intersection_pct_of_gp": pct,
                }
            )

        for row in memberships:
            membership_rows.append(row)

        containing_names = {
            norm(x["block_name"])
            for x in memberships
            if x["intersection_pct_of_gp"] > 99.999
        }

        selected_membership = [
            x for x in memberships
            if norm(x["block_name"])
            == norm(selected_block_gdf.iloc[0].get("block_name", ""))
            and norm(x["district"])
            == norm(selected_block_gdf.iloc[0].get("district", ""))
            and norm(x["state"])
            == norm(selected_block_gdf.iloc[0].get("state", ""))
        ]

        if not valid:
            spatial_status = "GEOMETRY_INVALID"
        elif not selected_intersects:
            spatial_status = "OUTSIDE_SELECTED_BLOCK"
        elif selected_within:
            spatial_status = "WITHIN_SELECTED_BLOCK"
        elif len(memberships) > 1:
            spatial_status = "CROSS_BLOCK_SOURCE"
        else:
            spatial_status = "PARTIAL_BLOCK_INTERSECTION"

        source_rows.append(
            {
                "gp_id": gp_id,
                "gp_name": gp_name,
                "source_index": int(idx),
                "source_geometry_signature": geometry_signature(
                    gp.loc[idx, "geometry"]
                ),
                "geometry_type": (
                    geom.geom_type
                    if geom is not None
                    else "EMPTY"
                ),
                "geometry_valid": valid,
                "source_area_km2": (
                    source_area / 1_000_000.0
                    if source_area > 0
                    else 0.0
                ),
                "selected_block_intersection_km2": (
                    selected_area / 1_000_000.0
                ),
                "selected_block_intersection_pct": selected_pct,
                "fully_within_selected_block": selected_within,
                "intersects_selected_block": selected_intersects,
                "spatial_status": spatial_status,
                "official_block_membership_count": len(
                    memberships
                ),
                "official_block_names": " | ".join(
                    sorted(
                        {
                            str(x["block_name"])
                            for x in memberships
                        }
                    )
                ),
            }
        )

    source_audit = pd.DataFrame(source_rows)
    membership_df = pd.DataFrame(membership_rows)

    # -------------------------------------------------------------
    # Same-ID relationships
    # -------------------------------------------------------------

    same_id_rows = []

    for gp_id in sorted(duplicate_ids):

        indices = list(
            gp_m.index[
                gp_m["_gp_id_norm"] == gp_id
            ]
        )
        indices = sorted(indices, key=lambda x: str(x))

        for i in range(len(indices)):
            for j in range(i + 1, len(indices)):

                a = gp_m.loc[
                    indices[i],
                    "geometry"
                ]
                b = gp_m.loc[
                    indices[j],
                    "geometry"
                ]

                equal = bool(
                    a is not None
                    and b is not None
                    and not a.is_empty
                    and not b.is_empty
                    and a.equals(b)
                )

                overlap = safe_intersection_area(a, b)

                if equal:
                    relationship = "IDENTICAL"
                elif (
                    a is not None
                    and b is not None
                    and not a.is_empty
                    and not b.is_empty
                    and a.contains(b)
                ):
                    relationship = "A_CONTAINS_B"
                elif (
                    a is not None
                    and b is not None
                    and not a.is_empty
                    and not b.is_empty
                    and b.contains(a)
                ):
                    relationship = "B_CONTAINS_A"
                elif overlap > AREA_EPSILON_M2:
                    relationship = "OVERLAPPING"
                else:
                    relationship = "DISJOINT"

                same_id_rows.append(
                    {
                        "gp_id": gp_id,
                        "record_a": i + 1,
                        "record_b": j + 1,
                        "name_a": gp.loc[
                            indices[i],
                            "_gp_name_norm",
                        ],
                        "name_b": gp.loc[
                            indices[j],
                            "_gp_name_norm",
                        ],
                        "geometry_equal": equal,
                        "spatial_relationship": relationship,
                        "overlap_area_km2": (
                            overlap / 1_000_000.0
                            if overlap == overlap
                            else float("nan")
                        ),
                    }
                )

    same_id_df = pd.DataFrame(same_id_rows)

    # -------------------------------------------------------------
    # Cross-GP positive-area overlap
    # -------------------------------------------------------------

    cross_rows = []
    gp_sindex = gp_m.sindex

    for idx in gp_m.index:

        geom = gp_m.loc[idx, "geometry"]
        gp_id = gp_m.loc[idx, "_gp_id_norm"]

        if geom is None or geom.is_empty:
            continue

        candidates = gp_sindex.query(
            geom,
            predicate="intersects",
        )

        for other_idx in candidates:

            if int(other_idx) <= int(idx):
                continue

            other_id = gp_m.loc[
                other_idx,
                "_gp_id_norm"
            ]

            if other_id == gp_id:
                continue

            other_geom = gp_m.loc[
                other_idx,
                "geometry"
            ]

            overlap = safe_intersection_area(
                geom,
                other_geom,
            )

            if overlap <= AREA_EPSILON_M2:
                continue

            area_a = float(geom.area)
            area_b = float(other_geom.area)

            cross_rows.append(
                {
                    "gp_id": gp_id,
                    "gp_name": gp_m.loc[
                        idx,
                        "_gp_name_norm",
                    ],
                    "source_index": int(idx),
                    "other_gp_id": other_id,
                    "other_gp_name": gp_m.loc[
                        other_idx,
                        "_gp_name_norm",
                    ],
                    "overlap_area_km2": (
                        overlap / 1_000_000.0
                    ),
                    "overlap_pct_of_gp": (
                        100.0 * overlap / area_a
                        if area_a > 0 else 0.0
                    ),
                    "overlap_pct_of_other_gp": (
                        100.0 * overlap / area_b
                        if area_b > 0 else 0.0
                    ),
                }
            )

    cross_df = pd.DataFrame(cross_rows)

    # -------------------------------------------------------------
    # Logical GP master
    # -------------------------------------------------------------

    master_rows = []

    for gp_id, group in gp.groupby(
        "_gp_id_norm",
        sort=True,
    ):

        source_indices = list(group.index)

        names = [
            str(x).strip()
            for x in group["_gp_name_norm"].tolist()
        ]

        unique_names = list(
            dict.fromkeys(
                norm(x) for x in names
            )
        )

        source_geometries = [
            g for g in group.geometry
            if g is not None
            and not g.is_empty
        ]

        source_count = len(source_geometries)

        if not source_geometries:
            raise RuntimeError(
                f"GP ID {gp_id} has no geometry."
            )

        # Never use an arbitrary polygon.
        source_union = unary_union(
            [
                make_valid_safe(g)
                for g in source_geometries
            ]
        )

        if source_union is None or source_union.is_empty:
            raise RuntimeError(
                f"GP ID {gp_id} produced empty source union."
            )

        source_union_m = source_union

        # Analysis geometry is limited to the requested Block.
        analysis_geom = polygonal_only(
            safe_intersection(
                source_union_m,
                selected_block_geom,
            )
        )

        source_valid = all(
            g.is_valid
            for g in source_geometries
        )

        source_unique_geometries = len(
            {
                geometry_signature(g)
                for g in source_geometries
            }
        )

        group_audit = source_audit[
            source_audit["gp_id"] == gp_id
        ]

        has_cross_block = bool(
            (
                group_audit["spatial_status"]
                == "CROSS_BLOCK_SOURCE"
            ).any()
        )

        has_outside = bool(
            (
                group_audit[
                    "selected_block_intersection_pct"
                ] < 99.999999
            ).any()
        )

        selected_area = (
            float(analysis_geom.area)
            if analysis_geom is not None
            and not analysis_geom.is_empty
            else 0.0
        )

        source_area = float(
            source_union_m.area
        )

        selected_pct = (
            100.0 * selected_area / source_area
            if source_area > 0
            else 0.0
        )

        # Name conflict is always retained as a conflict.
        if len(unique_names) > 1:
            identity_status = "NAME_CONFLICT"
        elif not source_valid:
            identity_status = "GEOMETRY_INVALID"
        elif source_count == 1:
            identity_status = "VALID_SINGLE"
        elif (
            source_unique_geometries == 1
        ):
            identity_status = "EXACT_DUPLICATE"
        elif has_cross_block:
            identity_status = "CROSS_BLOCK_SOURCE"
        elif has_outside:
            identity_status = "PARTIAL_BLOCK_INTERSECTION"
        else:
            identity_status = "VALID_MULTIPART"

        if identity_status == "NAME_CONFLICT":
            resolution = "RETAIN_FLAGGED"
        elif identity_status == "GEOMETRY_INVALID":
            resolution = "RETAIN_FLAGGED"
        elif identity_status == "EXACT_DUPLICATE":
            resolution = "DEDUPE_IDENTICAL_GEOMETRY"
        elif identity_status in {
            "VALID_SINGLE",
            "VALID_MULTIPART",
        }:
            resolution = "DISSOLVE_BY_GP_ID"
        elif identity_status in {
            "CROSS_BLOCK_SOURCE",
            "PARTIAL_BLOCK_INTERSECTION",
        }:
            resolution = "RETAIN_SOURCE_AND_CLIP_FOR_ANALYSIS"
        else:
            resolution = "RETAIN_FLAGGED"

        # Source geometry stays authoritative and is exported as WKT.
        source_wkt = source_union.wkt

        # The GeoJSON geometry is the analysis geometry when available.
        # This avoids using out-of-block area during feature extraction.
        # The original union is preserved in source_geometry_wkt.
        output_geom = (
            analysis_geom
            if analysis_geom is not None
            and not analysis_geom.is_empty
            else source_union
        )

        master_rows.append(
            {
                "gp_id": str(gp_id),
                "gp_name": (
                    names[0]
                    if names
                    else ""
                ),
                "source_feature_count": source_count,
                "source_unique_geometry_count": (
                    source_unique_geometries
                ),
                "geometry_status": identity_status,
                "resolution": resolution,
                "source_area_km2": (
                    source_area / 1_000_000.0
                ),
                "analysis_area_km2": (
                    selected_area / 1_000_000.0
                ),
                "analysis_coverage_pct_of_source": (
                    selected_pct
                ),
                "source_geometry_wkt": source_wkt,
                "analysis_geometry_type": (
                    output_geom.geom_type
                ),
                "geometry": output_geom,
            }
        )

    master = gpd.GeoDataFrame(
        master_rows,
        geometry="geometry",
        crs="EPSG:4326",
    )

    # Calculate final centroid in projected CRS.
    master_m = master.to_crs(metric_epsg)

    centroids = master_m.geometry.centroid
    centroid_gdf = gpd.GeoSeries(
        centroids,
        crs=f"EPSG:{metric_epsg}",
    ).to_crs(4326)

    master["centroid_lat"] = [
        float(g.y) if g is not None else float("nan")
        for g in centroid_gdf
    ]
    master["centroid_lon"] = [
        float(g.x) if g is not None else float("nan")
        for g in centroid_gdf
    ]

    return (
        source_audit,
        same_id_df,
        membership_df,
        cross_df,
        master,
    )


# ---------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------

def main():

    warnings.filterwarnings(
        "ignore",
        message="Unverified HTTPS request",
    )

    print("=" * 70)
    print("SIH26 - UNIVERSAL GP BOUNDARY INGESTION")
    print("=" * 70)

    state = input(
        "Enter State   : "
    ).strip()
    district = input(
        "Enter District: "
    ).strip()
    block = input(
        "Enter Block    : "
    ).strip()

    state_dir = clean_name(state)
    district_dir = clean_name(district)
    block_dir = clean_name(block)

    block_root = (
        PROJECT_ROOT
        / "gp"
        / state_dir
        / district_dir
        / block_dir
    )

    raw_dir = block_root / "raw"
    raw_boundary_dir = raw_dir / "boundaries"
    processed_dir = block_root / "processed"
    metadata_dir = block_root / "metadata"

    for directory in [
        raw_boundary_dir,
        processed_dir,
        metadata_dir,
    ]:
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    print("\nProject directory:")
    print(f"  {block_root}")

    # -------------------------------------------------------------
    # 1. RESOLVE REQUESTED BLOCK + RETAIN COMPLETE BLOCK LAYER
    # -------------------------------------------------------------

    print(
        "\n[1/6] Resolving official Block layer..."
    )

    block_records = fetch_all_block_records()

    print(
        f"\nTotal Block records retrieved: "
        f"{len(block_records)}"
    )

    all_blocks = build_block_gdf(
        block_records
    )

    selected_block = choose_block_record(
        block_records,
        state,
        district,
        block,
    )

    print(
        f"Matching Block records: "
        f"{len(selected_block)}"
    )

    if selected_block.empty:
        raise RuntimeError(
            "Selected Block has no geometry."
        )

    selected_block_geom = unary_union(
        [
            g for g in selected_block.geometry
            if g is not None
            and not g.is_empty
        ]
    )

    if selected_block_geom.is_empty:
        raise RuntimeError(
            "Selected Block geometry is empty."
        )

    block_lgd_values = sorted(
        {
            str(x)
            for x in selected_block[
                "block_lgd"
            ].dropna()
        }
    ) if "block_lgd" in selected_block.columns else []

    block_code11_values = sorted(
        {
            str(x)
            for x in selected_block[
                "blkcode11"
            ].dropna()
        }
    ) if "blkcode11" in selected_block.columns else []

    if len(block_lgd_values) != 1:
        raise RuntimeError(
            "Selected Block does not resolve to one "
            f"LGD code: {block_lgd_values}"
        )

    block_lgd = block_lgd_values[0]
    block_code11 = (
        block_code11_values[0]
        if block_code11_values
        else ""
    )

    print("\nBlock successfully resolved:")
    print(
        f"  State       : "
        f"{norm(selected_block.iloc[0].get('state'))}"
    )
    print(
        f"  District    : "
        f"{selected_block.iloc[0].get('district')}"
    )
    print(
        f"  Block       : "
        f"{norm(selected_block.iloc[0].get('block_name'))}"
    )
    print(
        f"  Block LGD   : {block_lgd}"
    )
    print(
        f"  Block Code11: {block_code11}"
    )

    # Save raw official Block snapshot.
    block_timestamp = datetime.now(
        timezone.utc
    ).strftime("%Y%m%dT%H%M%SZ")

    block_snapshot = (
        raw_boundary_dir
        / f"gram_manchitra_all_blocks_"
        f"{block_timestamp}.geojson"
    )

    all_blocks.to_file(
        block_snapshot,
        driver="GeoJSON",
    )

    # -------------------------------------------------------------
    # 2. COLLECT GP SOURCE
    # -------------------------------------------------------------

    print(
        "\n[2/6] Collecting official GP boundaries..."
    )
    print(
        f"  Block LGD: {block_lgd}"
    )
    print(
        "  Source: Official Gram Manchitra"
    )

    gp = query_block_gps(
        block_lgd
    )

    if gp is None or gp.empty:
        raise RuntimeError(
            "Official Gram Manchitra returned no GP polygons."
        )

    if gp.crs is None:
        raise RuntimeError(
            "Official GP layer has no CRS."
        )

    gp = gp.to_crs(4326)

    gp_timestamp = datetime.now(
        timezone.utc
    ).strftime("%Y%m%dT%H%M%SZ")

    raw_gp_file = (
        raw_boundary_dir
        / f"gram_manchitra_gp_"
        f"{gp_timestamp}.geojson"
    )

    gp.to_file(
        raw_gp_file,
        driver="GeoJSON",
    )

    print(
        f"  GP source features: {len(gp)}"
    )
    print(
        f"  Raw GP snapshot: {raw_gp_file}"
    )

    # -------------------------------------------------------------
    # 3. DETECT FIELDS + BASIC GEOMETRY
    # -------------------------------------------------------------

    print(
        "\n[3/6] Detecting fields and validating geometry..."
    )

    gp_id_col = find_column(
        gp.columns,
        [
            "gp_id",
            "gpcode",
            "gp_code",
            "gp_lgd",
            "gp_lgd_code",
            "gplgdcode",
        ],
    )

    gp_name_col = find_column(
        gp.columns,
        [
            "gp_name",
            "gpname",
            "gram_panchayat_name",
            "panchayat_name",
        ],
    )

    if gp_id_col is None:
        raise RuntimeError(
            "Could not identify GP ID column.\n"
            f"Available columns: {list(gp.columns)}"
        )

    if gp_name_col is None:
        raise RuntimeError(
            "Could not identify GP name column.\n"
            f"Available columns: {list(gp.columns)}"
        )

    print(
        f"  GP ID column  : {gp_id_col}"
    )
    print(
        f"  GP name column: {gp_name_col}"
    )

    validation = validate_geometry(
        gp,
        require_polygon=True,
    )

    if isinstance(validation, dict):
        print(
            "  Geometry validation:"
        )
        print(
            json.dumps(
                validation,
                indent=2,
            )
        )

        # Do not stop merely because repairable invalid topology exists.
        # Repair is attempted below and then checked again.
        if validation.get(
            "error_count",
            0,
        ) > 0:
            print(
                "  Attempting conservative geometry repair..."
            )

    gp = repair_invalid_geometry(
        gp
    )

    # Recheck after repair.
    validation_after = validate_geometry(
        gp,
        require_polygon=True,
    )

    if (
        isinstance(validation_after, dict)
        and validation_after.get(
            "error_count",
            0,
        ) > 0
    ):
        print(
            "\nWARNING: Some source geometries remain invalid."
        )
        print(
            "They will be retained and flagged; "
            "no geometry will be fabricated."
        )

    # -------------------------------------------------------------
    # 4. DYNAMIC SPATIAL DISCRIMINATION
    # -------------------------------------------------------------

    print(
        "\n[4/6] Dynamically classifying GP source geometries..."
    )

    metric_epsg = get_utm_epsg(
        selected_block
    )

    print(
        f"  Metric CRS: EPSG:{metric_epsg}"
    )

    (
        source_audit,
        same_id_df,
        membership_df,
        cross_df,
        master,
    ) = classify_source_parts(
        gp=gp,
        block_all=all_blocks,
        selected_block_gdf=selected_block,
        gp_id_col=gp_id_col,
        gp_name_col=gp_name_col,
        metric_epsg=metric_epsg,
    )

    duplicate_count = int(
        (
            gp[gp_id_col]
            .astype(str)
            .str.strip()
            .value_counts()
            > 1
        ).sum()
    )

    print(
        f"  Source GP features : {len(gp)}"
    )
    print(
        f"  Unique GP IDs      : {len(master)}"
    )
    print(
        f"  Repeated GP IDs    : {duplicate_count}"
    )

    print(
        "\n  Dynamic classifications:"
    )

    classification_counts = (
        master["geometry_status"]
        .value_counts()
        .sort_index()
    )

    for label, count in (
        classification_counts.items()
    ):
        print(
            f"    {label:<30} {int(count)}"
        )

    # -------------------------------------------------------------
    # 5. SAVE AUDIT + MASTER
    # -------------------------------------------------------------

    print(
        "\n[5/6] Saving provenance and GP master..."
    )

    source_audit_file = (
        processed_dir
        / "duplicate_gp_source_audit.csv"
    )

    same_id_file = (
        processed_dir
        / "duplicate_gp_same_id_relationships.csv"
    )

    membership_file = (
        processed_dir
        / "gp_official_block_membership.csv"
    )

    cross_file = (
        processed_dir
        / "gp_cross_overlap.csv"
    )

    source_audit.to_csv(
        source_audit_file,
        index=False,
    )

    same_id_df.to_csv(
        same_id_file,
        index=False,
    )

    membership_df.to_csv(
        membership_file,
        index=False,
    )

    cross_df.to_csv(
        cross_file,
        index=False,
    )

    master["state"] = state
    master["district"] = district
    master["block"] = block
    master["block_lgd"] = block_lgd
    master["block_code11"] = block_code11
    master["source_layer"] = (
        "Official Gram Manchitra GP"
    )
    master["source_snapshot"] = (
        raw_gp_file.name
    )
    master["block_snapshot"] = (
        block_snapshot.name
    )
    master["synthetic_geometry"] = False

    preferred = [
        "gp_id",
        "gp_name",
        "source_feature_count",
        "source_unique_geometry_count",
        "geometry_status",
        "resolution",
        "source_area_km2",
        "analysis_area_km2",
        "analysis_coverage_pct_of_source",
        "analysis_geometry_type",
        "centroid_lat",
        "centroid_lon",
        "state",
        "district",
        "block",
        "block_lgd",
        "block_code11",
        "source_layer",
        "source_snapshot",
        "block_snapshot",
        "synthetic_geometry",
        "source_geometry_wkt",
        "geometry",
    ]

    master = master[
        [
            c for c in preferred
            if c in master.columns
        ]
    ]

    master_geojson = (
        processed_dir
        / "gp_master.geojson"
    )

    master_csv = (
        processed_dir
        / "gp_master.csv"
    )

    master.to_file(
        master_geojson,
        driver="GeoJSON",
    )

    csv_master = master.copy()

    csv_master["geometry_wkt"] = (
        csv_master.geometry.to_wkt()
    )

    csv_master = csv_master.drop(
        columns=["geometry"]
    )

    csv_master.to_csv(
        master_csv,
        index=False,
    )

    # -------------------------------------------------------------
    # 6. METADATA
    # -------------------------------------------------------------

    print(
        "\n[6/6] Writing metadata and final QC..."
    )

    outside_count = int(
        (
            master["geometry_status"]
            .isin(
                [
                    "CROSS_BLOCK_SOURCE",
                    "PARTIAL_BLOCK_INTERSECTION",
                    "OUTSIDE_SELECTED_BLOCK",
                ]
            )
        ).sum()
    )

    flagged_count = int(
        (
            master["geometry_status"]
            .isin(
                [
                    "NAME_CONFLICT",
                    "GEOMETRY_INVALID",
                ]
            )
        ).sum()
    )

    metadata = {
        "generated_utc": datetime.now(
            timezone.utc
        ).isoformat(),
        "pipeline": (
            "SIH26 Universal GP Boundary "
            "Ingestion Engine"
        ),
        "state": state,
        "district": district,
        "block": block,
        "block_lgd": block_lgd,
        "block_code11": block_code11,
        "gp_source": (
            "Official Gram Manchitra"
        ),
        "block_source": (
            BLOCK_QUERY_URL
        ),
        "gp_id_column": gp_id_col,
        "gp_name_column": gp_name_col,
        "metric_epsg": int(metric_epsg),
        "raw_gp_feature_count": int(len(gp)),
        "final_unique_gp_count": int(len(master)),
        "repeated_gp_id_count": duplicate_count,
        "cross_gp_positive_area_overlap_count": int(
            len(cross_df)
        ),
        "outside_or_partial_source_count": outside_count,
        "flagged_conflict_count": flagged_count,
        "raw_gp_modified": False,
        "synthetic_geometry": False,
        "analysis_geometry_policy": (
            "For source geometry extending beyond the selected "
            "Block, retain the official source geometry in "
            "source_geometry_wkt and use the polygonal "
            "intersection with the selected Block as the "
            "GeoJSON analysis geometry."
        ),
        "duplicate_policy": (
            "Repeated GP IDs are discriminated dynamically "
            "using identity, geometry equality, geometry "
            "validity, complete official Block membership, "
            "cross-Block membership and cross-GP overlap. "
            "No largest-polygon or arbitrary-drop rule is used."
        ),
        "outputs": {
            "gp_master_geojson": str(
                master_geojson
            ),
            "gp_master_csv": str(
                master_csv
            ),
            "source_audit": str(
                source_audit_file
            ),
            "same_id_relationships": str(
                same_id_file
            ),
            "official_block_membership": str(
                membership_file
            ),
            "cross_gp_overlap": str(
                cross_file
            ),
            "raw_gp_snapshot": str(
                raw_gp_file
            ),
            "raw_block_snapshot": str(
                block_snapshot
            ),
        },
    }

    metadata_file = (
        metadata_dir
        / "gp_boundary_metadata.json"
    )

    with open(
        metadata_file,
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            metadata,
            f,
            indent=2,
        )

    # -------------------------------------------------------------
    # FINAL REPORT
    # -------------------------------------------------------------

    print(
        "\n" + "=" * 70
    )
    print(
        "GP BOUNDARY INGESTION COMPLETE"
    )
    print(
        "=" * 70
    )

    print(
        f"\nRaw official GP features : {len(gp)}"
    )
    print(
        f"Final logical GP units   : {len(master)}"
    )
    print(
        f"Repeated GP IDs          : {duplicate_count}"
    )

    print(
        "\nResolution summary:"
    )

    for label, count in (
        master["geometry_status"]
        .value_counts()
        .sort_index()
        .items()
    ):
        print(
            f"  {label:<30} {int(count)}"
        )

    print(
        "\nSource safeguards:"
    )
    print(
        "  Raw GP snapshot preserved : YES"
    )
    print(
        "  Raw Block snapshot saved  : YES"
    )
    print(
        "  Blind duplicate deletion  : NO"
    )
    print(
        "  Largest-polygon selection : NO"
    )
    print(
        "  Synthetic geometry        : NO"
    )
    print(
        "  Dynamic Block membership  : YES"
    )
    print(
        "  Out-of-block source retained: YES"
    )
    print(
        "  Analysis geometry clipped : YES"
    )

    print(
        "\nOutputs:"
    )
    print(
        f"  GP master       : {master_geojson}"
    )
    print(
        f"  GP CSV          : {master_csv}"
    )
    print(
        f"  Source audit    : {source_audit_file}"
    )
    print(
        f"  Block membership: {membership_file}"
    )
    print(
        f"  Metadata        : {metadata_file}"
    )

    print(
        "\n" + "=" * 70
    )


if __name__ == "__main__":
    main()
