
# -*- coding: utf-8 -*-
"""
SIH26 — Dynamic GP-wise Weather Forecast Map
============================================

Run:
    streamlit run gp_weather_dashboard.py

The app is block-generic. It discovers completed Stage-2 outputs under:
    <PROJECT_ROOT>/models/main_model/stage2_direct_gp_training/<State>/<District>/<Block>/

It reads:
    stage2_current_gp_forecast.csv

and automatically locates GP spatial data containing:
    gp_id
    latitude/longitude columns

Optional:
    GeoJSON boundary files are discovered automatically if available.

Expected forecast columns:
    gp_id
    target_date
    forecast_horizon_day
    gp_temperature_corrected
    gp_humidity_corrected
    gp_precipitation_corrected
    gp_wind_corrected
    plus corresponding block_*_raw columns.

This dashboard does NOT retrain the model. It visualizes the forecast
already generated by Stage 1 + Stage 2.
"""

import json
import re
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st
import folium
from folium.plugins import Fullscreen
from streamlit_folium import st_folium
from shapely.geometry import shape, mapping

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]
STAGE2_ROOT = PROJECT_ROOT / "models" / "main_model" / "stage2_direct_gp_training"
GP_ROOT = PROJECT_ROOT / "gp"

st.set_page_config(
    page_title="SIH26 — GP Weather Forecast",
    page_icon="🌦️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------
# Styling
# ---------------------------------------------------------------------

st.markdown(
    """
    <style>
    .main-title {
        font-size: 30px;
        font-weight: 750;
        margin-bottom: 0;
    }
    .sub-title {
        color: #667085;
        font-size: 15px;
        margin-bottom: 18px;
    }
    .metric-card {
        border: 1px solid #e5e7eb;
        border-radius: 10px;
        padding: 12px;
        background: white;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Generic discovery helpers
# ---------------------------------------------------------------------

def safe_label(x):
    return str(x).replace("_", " ").title()


def discover_blocks():
    """Return completed Stage-2 blocks that contain a current forecast."""
    blocks = []
    if not STAGE2_ROOT.exists():
        return blocks

    for forecast_file in STAGE2_ROOT.glob("*/*/*/stage2_current_gp_forecast.csv"):
        rel = forecast_file.relative_to(STAGE2_ROOT)
        if len(rel.parts) != 4:
            continue
        state, district, block, _ = rel.parts
        blocks.append(
            {
                "state": state,
                "district": district,
                "block": block,
                "forecast_file": forecast_file,
            }
        )

    return sorted(blocks, key=lambda x: (x["state"], x["district"], x["block"]))


def normalize_columns(df):
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    return df


def find_coordinate_columns(df):
    """Find GP latitude/longitude columns from the existing GP feature table."""
    cols = list(df.columns)

    lat_candidates = [
        "landcover__centroid_lat",
        "centroid_lat",
        "latitude",
        "lat",
        "gp_lat",
        "gp_latitude",
    ]
    lon_candidates = [
        "landcover__centroid_lon",
        "centroid_lon",
        "longitude",
        "lon",
        "lng",
        "gp_lon",
        "gp_longitude",
    ]

    lat = next((c for c in lat_candidates if c in cols), None)
    lon = next((c for c in lon_candidates if c in cols), None)

    if lat and lon:
        return lat, lon

    # Fallback: fuzzy search
    lat = next((c for c in cols if "lat" in c.lower() and "lon" not in c.lower()), None)
    lon = next((c for c in cols if "lon" in c.lower() or "lng" in c.lower()), None)
    return lat, lon


def find_gp_feature_file(state, district, block):
    """
    Locate the merged/static GP feature table for the selected block.

    We deliberately inspect column names instead of assuming one exact filename,
    because the upstream GP collector may change its filename while preserving
    the GP feature contract.
    """
    search_roots = [
        GP_ROOT / state / district / block,
        PROJECT_ROOT / "datasets" / "cleaned" / state / district / block,
        PROJECT_ROOT / "datasets" / "engineered" / state / district / block,
    ]

    candidates = []
    for root in search_roots:
        if not root.exists():
            continue
        candidates.extend(root.rglob("*.csv"))

    # Also search the whole GP tree as a fallback.
    if not candidates and GP_ROOT.exists():
        candidates = list(GP_ROOT.rglob("*.csv"))

    best = None
    best_score = -1

    for f in candidates:
        try:
            # Avoid reading enormous unrelated files where possible.
            sample = pd.read_csv(f, nrows=3)
            sample = normalize_columns(sample)
            lat, lon = find_coordinate_columns(sample)
            has_gp = "gp_id" in sample.columns or any(
                c.lower() in {"gpcode", "gp_code", "panchayat_code"} for c in sample.columns
            )

            if not (lat and lon and has_gp):
                continue

            score = 10
            name = f.name.lower()
            if "merge" in name:
                score += 5
            if "gp" in name:
                score += 2
            if "feature" in name:
                score += 2

            if score > best_score:
                best = f
                best_score = score
        except Exception:
            continue

    return best


def find_boundary_file(state, district, block):
    """
    Locate the OFFICIAL requested block boundary.

    Important:
    - The project contains both Block GeoJSON and GP GeoJSON files.
    - The previous implementation could accidentally select a GP file,
      producing a few disconnected polygons instead of the complete block.
    - We therefore validate the GeoJSON properties and require the selected
      feature to match the requested state/district/block.
    """
    roots = [
        GP_ROOT / state / district / block,
        PROJECT_ROOT / "datasets" / "cleaned" / state / district / block,
    ]

    candidates = []
    for root in roots:
        if root.exists():
            candidates.extend(root.rglob("*.geojson"))
            candidates.extend(root.rglob("*.json"))

    def norm(v):
        return str(v or "").strip().upper().replace("_", " ").replace("-", " ")

    valid_block_candidates = []

    for f in candidates:
        try:
            with open(f, "r", encoding="utf-8") as fh:
                obj = json.load(fh)

            if obj.get("type") != "FeatureCollection":
                continue

            features = obj.get("features", [])
            if not features:
                continue

            # Look for a feature whose administrative identity matches
            # the selected block.
            matched = False
            polygon_count = 0

            for feature in features:
                props = feature.get("properties", {}) or {}
                geom = feature.get("geometry") or {}
                gtype = geom.get("type", "")

                if gtype in {"Polygon", "MultiPolygon"}:
                    polygon_count += 1

                state_val = props.get("state", props.get("stname", ""))
                district_val = props.get("district", props.get("dtname", ""))
                block_val = props.get(
                    "block_name",
                    props.get("blkname", props.get("block", ""))
                )

                if (
                    norm(state_val) == norm(state)
                    and norm(district_val) == norm(district)
                    and norm(block_val) == norm(block)
                ):
                    matched = True

            if not matched:
                continue

            name = f.name.lower()

            # Strong preference for the official Block snapshot produced by
            # 01_gp_boundary.py. Never prefer a GP snapshot merely because
            # its filename contains "boundary".
            score = 100

            if "all_blocks" in name:
                score += 100
            if "block" in name:
                score += 50
            if "gram_manchitra" in name:
                score += 20
            if "gp" in name:
                score -= 100
            if "panchayat" in name:
                score -= 50

            # A one-feature polygon matching the requested block is ideal.
            if len(features) == 1 and polygon_count == 1:
                score += 30

            valid_block_candidates.append((score, f))

        except Exception:
            continue

    if not valid_block_candidates:
        return None

    valid_block_candidates.sort(
        key=lambda x: (-x[0], str(x[1]))
    )

    return valid_block_candidates[0][1]


def find_gp_boundary_file(state, district, block):
    """
    Locate the processed official GP master geometry for the selected block.

    Priority:
      1. gp_master.geojson produced by 01_gp_boundary.py
      2. raw Gram Manchitra GP GeoJSON snapshots

    The GP layer is drawn as an overlay; weather markers remain on top.
    """
    roots = [
        GP_ROOT / state / district / block,
        PROJECT_ROOT / "datasets" / "cleaned" / state / district / block,
    ]

    candidates = []
    for root in roots:
        if root.exists():
            candidates.extend(root.rglob("*.geojson"))

    # Strong preference for the processed logical GP master.
    preferred = [
        f for f in candidates
        if f.name.lower() == "gp_master.geojson"
    ]
    if preferred:
        return preferred[0]

    # Fallback to official Gram Manchitra GP snapshots.
    preferred = [
        f for f in candidates
        if "gram_manchitra_gp" in f.name.lower()
    ]
    if preferred:
        preferred.sort(key=lambda x: x.stat().st_mtime, reverse=True)
        return preferred[0]

    return None


def load_forecast(forecast_file):
    df = pd.read_csv(forecast_file)
    df = normalize_columns(df)

    required = [
        "gp_id",
        "target_date",
        "forecast_horizon_day",
        "gp_temperature_corrected",
        "gp_humidity_corrected",
        "gp_precipitation_corrected",
        "gp_wind_corrected",
    ]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Forecast file is missing columns: {missing}")

    df["gp_id"] = df["gp_id"].astype(str)
    df["target_date"] = pd.to_datetime(df["target_date"], errors="coerce")
    df["forecast_horizon_day"] = pd.to_numeric(
        df["forecast_horizon_day"], errors="coerce"
    ).astype("Int64")

    return df


def load_gp_features(feature_file):
    gp = pd.read_csv(feature_file)
    gp = normalize_columns(gp)

    if "gp_id" not in gp.columns:
        # Common alternatives
        alt = next(
            (c for c in gp.columns if c.lower() in {"gpcode", "gp_code", "panchayat_code"}),
            None,
        )
        if alt:
            gp["gp_id"] = gp[alt].astype(str)
        else:
            raise ValueError("GP feature file has no gp_id column.")

    lat_col, lon_col = find_coordinate_columns(gp)
    if not lat_col or not lon_col:
        raise ValueError(
            "Could not find GP latitude/longitude columns in the GP feature table."
        )

    gp["gp_id"] = gp["gp_id"].astype(str)
    gp["latitude"] = pd.to_numeric(gp[lat_col], errors="coerce")
    gp["longitude"] = pd.to_numeric(gp[lon_col], errors="coerce")

    gp = gp.dropna(subset=["latitude", "longitude"])
    gp = gp.drop_duplicates("gp_id")

    # Keep a useful GP display name if available.
    name_candidates = [
        "gp_name",
        "GP_NAME",
        "gpname",
        "gram_panchayat_name",
        "panchayat_name",
        "name",
    ]
    name_col = next((c for c in name_candidates if c in gp.columns), None)
    if name_col:
        gp["display_name"] = gp[name_col].astype(str)
    else:
        gp["display_name"] = "GP " + gp["gp_id"]

    return gp


# ---------------------------------------------------------------------
# Forecast reshaping
# ---------------------------------------------------------------------

VARIABLES = {
    "Temperature": {
        "forecast": "gp_temperature_corrected",
        "raw": "block_temperature_raw",
        "unit": "°C",
        "icon": "🌡️",
        "palette": "RdYlBu_r",
    },
    "Humidity": {
        "forecast": "gp_humidity_corrected",
        "raw": "block_humidity_raw",
        "unit": "%",
        "icon": "💧",
        "palette": "Blues",
    },
    "Precipitation": {
        "forecast": "gp_precipitation_corrected",
        "raw": "block_precipitation_raw",
        "unit": "mm",
        "icon": "🌧️",
        "palette": "YlGnBu",
    },
    "Wind Speed": {
        "forecast": "gp_wind_corrected",
        "raw": "block_wind_raw",
        "unit": "m/s",
        "icon": "💨",
        "palette": "PuBuGn",
    },
}


def merge_forecast_and_gps(forecast, gps):
    out = forecast.merge(
        gps[["gp_id", "display_name", "latitude", "longitude"]],
        on="gp_id",
        how="left",
        validate="many_to_one",
    )
    return out.dropna(subset=["latitude", "longitude"])


def color_for_value(value, vmin, vmax, variable):
    """Simple dynamic color scale without requiring geopandas."""
    if not np.isfinite(value):
        return "#808080"

    if vmax <= vmin:
        t = 0.5
    else:
        t = float((value - vmin) / (vmax - vmin))
        t = max(0.0, min(1.0, t))

    # Compact palettes designed for map markers.
    if variable == "Temperature":
        stops = [
            (0.0, "#2b83ba"),
            (0.25, "#abdda4"),
            (0.5, "#ffffbf"),
            (0.75, "#fdae61"),
            (1.0, "#d7191c"),
        ]
    elif variable == "Humidity":
        stops = [
            (0.0, "#eff3ff"),
            (0.35, "#9ecae1"),
            (0.7, "#3182bd"),
            (1.0, "#08519c"),
        ]
    elif variable == "Precipitation":
        stops = [
            (0.0, "#ffffcc"),
            (0.35, "#a1dab4"),
            (0.7, "#41b6c4"),
            (1.0, "#225ea8"),
        ]
    else:
        stops = [
            (0.0, "#f7fcfd"),
            (0.35, "#9ecae1"),
            (0.7, "#2c7fb8"),
            (1.0, "#253494"),
        ]

    for i in range(len(stops) - 1):
        a, ca = stops[i]
        b, cb = stops[i + 1]
        if t <= b:
            u = (t - a) / max(b - a, 1e-9)
            import matplotlib.colors as mcolors
            c1 = np.array(mcolors.to_rgb(ca))
            c2 = np.array(mcolors.to_rgb(cb))
            rgb = c1 * (1 - u) + c2 * u
            return mcolors.to_hex(rgb)

    return stops[-1][1]


@st.cache_data(show_spinner=False)
def load_simplified_geojson(boundary_file, allowed_gp_ids=None, tolerance=0.00015):
    """
    Load GeoJSON, optionally filter GP features, simplify geometry,
    and retain only the properties required by the dashboard.

    This prevents large GeoJSON payloads from being sent to the browser.
    """
    with open(boundary_file, "r", encoding="utf-8") as f:
        geo = json.load(f)

    allowed = None
    if allowed_gp_ids is not None:
        allowed = {str(x).strip() for x in allowed_gp_ids}

    compact_features = []

    for feature in geo.get("features", []):
        props = feature.get("properties", {}) or {}
        geom = feature.get("geometry")

        if not geom:
            continue

        # Identify GP ID from common property names.
        gp_id = None
        for key in [
            "gp_id",
            "GP_ID",
            "gpcode",
            "gp_code",
            "GP_CODE",
            "panchayat_code",
            "PANCHAYAT_CODE",
            "lgd_code",
            "LGD_CODE",
            "id",
            "ID",
        ]:
            if key in props and props[key] not in (None, ""):
                gp_id = str(props[key]).strip()
                break

        # When requested, retain only GPs belonging to the selected block.
        if allowed is not None:
            if gp_id is None or gp_id not in allowed:
                continue

        # Identify a compact display name.
        gp_name = None
        for key in [
            "gp_name",
            "GP_NAME",
            "gpname",
            "gram_panchayat_name",
            "GRAM_PANCHAYAT_NAME",
            "panchayat_name",
            "PANCHAYAT_NAME",
            "name",
            "NAME",
        ]:
            if key in props and props[key] not in (None, ""):
                gp_name = str(props[key])
                break

        if gp_name is None:
            gp_name = f"GP {gp_id}" if gp_id else "Gram Panchayat"

        # Simplify geometry while preserving topology.
        try:
            geom_obj = shape(geom)

            if not geom_obj.is_empty:
                geom_obj = geom_obj.simplify(
                    tolerance,
                    preserve_topology=True,
                )

            simplified_geometry = mapping(geom_obj)
        except Exception:
            simplified_geometry = geom

        compact_features.append(
            {
                "type": "Feature",
                "properties": {
                    "gp_id": gp_id or "",
                    "gp_name": gp_name,
                },
                "geometry": simplified_geometry,
            }
        )

    return {
        "type": "FeatureCollection",
        "features": compact_features,
    }


def add_boundary(m, boundary_file):
    """Add a simplified block boundary to the map."""
    if not boundary_file:
        return

    try:
        geo = load_simplified_geojson(
            str(boundary_file),
            allowed_gp_ids=None,
            tolerance=0.00015,
        )

        if not geo.get("features"):
            return

        folium.GeoJson(
            geo,
            name="Block Boundary",
            style_function=lambda _: {
                "fillColor": "#0d0101",
                "color": "#ffffff",
                "weight": 4,
                "fillOpacity": 0.03,
            },
        ).add_to(m)

    except Exception as exc:
        st.sidebar.warning(
            f"Block boundary could not be loaded: {exc}"
        )


def add_gp_boundaries(m, gp_boundary_file, gp_ids):
    """
    Add only the GP polygons needed for the currently selected block.

    This avoids sending the entire gp_master.geojson to the browser.
    """
    if not gp_boundary_file:
        return

    try:
        compact_geo = load_simplified_geojson(
            str(gp_boundary_file),
            allowed_gp_ids=tuple(sorted(str(x) for x in gp_ids)),
            tolerance=0.00015,
        )

        if not compact_geo.get("features"):
            st.sidebar.warning(
                "GP boundary file was found, but no matching GP IDs were found."
            )
            return

        folium.GeoJson(
            compact_geo,
            name="Gram Panchayat Boundaries",
            style_function=lambda _: {
                "fillColor": "#ffffff",
                "color": "#ffffff",
                "weight": 1.1,
                "opacity": 0.85,
                "fillOpacity": 0.0,
            },
            highlight_function=lambda _: {
                "color": "#00ffff",
                "weight": 2.5,
                "opacity": 1.0,
                "fillOpacity": 0.05,
            },
            tooltip=folium.GeoJsonTooltip(
                fields=["gp_name", "gp_id"],
                aliases=["Gram Panchayat", "GP ID"],
                localize=True,
                sticky=False,
                labels=True,
            ),
        ).add_to(m)

    except Exception as exc:
        st.sidebar.warning(
            f"GP boundary overlay could not be loaded: {exc}"
        )


def build_map(day_df, variable, selected_gp_id=None, boundary_file=None, gp_boundary_file=None):
    center_lat = day_df["latitude"].mean()
    center_lon = day_df["longitude"].mean()

    m = folium.Map(
        location=[center_lat, center_lon],
        zoom_start=10,
        control_scale=True,
        tiles=None,
    )

    # Satellite base similar to the requested visual.
    folium.TileLayer(
        tiles=(
            "https://server.arcgisonline.com/ArcGIS/rest/services/"
            "World_Imagery/MapServer/tile/{z}/{y}/{x}"
        ),
        attr="Esri World Imagery",
        name="Satellite",
        overlay=False,
        control=True,
    ).add_to(m)

    folium.TileLayer(
        "OpenStreetMap",
        name="Street Map",
        overlay=False,
        control=True,
    ).add_to(m)

    add_boundary(m, boundary_file)

    # -------------------------------------------------------------
    # Gram Panchayat boundary overlay
    # -------------------------------------------------------------
    add_gp_boundaries(
        m,
        gp_boundary_file,
        day_df["gp_id"].unique(),
    )


    cfg = VARIABLES[variable]
    val_col = cfg["forecast"]

    vals = pd.to_numeric(day_df[val_col], errors="coerce")
    vmin = float(vals.min())
    vmax = float(vals.max())

    for _, row in day_df.iterrows():
        value = float(row[val_col])
        color = color_for_value(value, vmin, vmax, variable)

        selected = str(row["gp_id"]) == str(selected_gp_id)

        popup_html = f"""
        <div style="font-family:Arial;min-width:250px">
          <h4 style="margin-bottom:6px">{row['display_name']}</h4>
          <b>GP ID:</b> {row['gp_id']}<br>
          <b>Coordinates:</b> {row['latitude']:.5f}, {row['longitude']:.5f}<br>
          <hr style="margin:7px 0">
          <b>D{int(row['forecast_horizon_day'])} — {row['target_date'].date()}</b><br>
          🌡️ Temperature: {row['gp_temperature_corrected']:.2f} °C<br>
          💧 Humidity: {row['gp_humidity_corrected']:.2f} %<br>
          🌧️ Precipitation: {row['gp_precipitation_corrected']:.2f} mm<br>
          💨 Wind: {row['gp_wind_corrected']:.2f} m/s
        </div>
        """

        folium.CircleMarker(
            location=[row["latitude"], row["longitude"]],
            radius=9 if selected else 7,
            color="#111827" if selected else "#ffffff",
            weight=3 if selected else 1,
            fill=True,
            fill_color=color,
            fill_opacity=0.92,
            popup=folium.Popup(popup_html, max_width=330),
            tooltip=f"{row['display_name']} — {value:.2f} {cfg['unit']}",
        ).add_to(m)

    Fullscreen(position="topright").add_to(m)
    folium.LayerControl(collapsed=False).add_to(m)

    return m


# ---------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------

blocks = discover_blocks()

if not blocks:
    st.error(
        "No completed Stage-2 blocks were found. "
        f"Expected folders under: {STAGE2_ROOT}"
    )
    st.stop()

st.markdown(
    '<div class="main-title">🌦️ SIH26 — Gram Panchayat Weather Forecast</div>',
    unsafe_allow_html=True,
)
st.markdown(
    '<div class="sub-title">Dynamic Stage-1 + Stage-2 spatial weather forecast dashboard</div>',
    unsafe_allow_html=True,
)

# Sidebar block selector
st.sidebar.header("Block Selection")

block_labels = [
    f"{b['state']} → {b['district']} → {b['block']}"
    for b in blocks
]

selected_idx = st.sidebar.selectbox(
    "Select Block",
    range(len(blocks)),
    format_func=lambda i: block_labels[i],
)

selected_block = blocks[selected_idx]

st.sidebar.caption(
    "The dashboard automatically uses the completed Stage-2 forecast "
    "generated for the selected block."
)

try:
    forecast = load_forecast(selected_block["forecast_file"])
except Exception as e:
    st.error(f"Could not load forecast: {e}")
    st.stop()

feature_file = find_gp_feature_file(
    selected_block["state"],
    selected_block["district"],
    selected_block["block"],
)

if feature_file is None:
    st.error(
        "Stage-2 forecast was found, but the GP spatial feature table "
        "with latitude/longitude could not be located."
    )
    st.info(
        "The app searches the block's GP folder and cleaned datasets for a CSV "
        "containing gp_id plus latitude/longitude."
    )
    st.stop()

try:
    gps = load_gp_features(feature_file)
except Exception as e:
    st.error(f"Could not load GP spatial data: {e}")
    st.stop()

data = merge_forecast_and_gps(forecast, gps)

if data.empty:
    st.error("No forecast rows could be joined to GP coordinates.")
    st.stop()

boundary_file = find_boundary_file(
    selected_block["state"],
    selected_block["district"],
    selected_block["block"],
)

if boundary_file:
    st.sidebar.success(
        f"Official block boundary loaded: {boundary_file.name}"
    )
else:
    st.sidebar.warning(
        "Official block boundary was not found. GP points will still be shown."
    )

gp_boundary_file = find_gp_boundary_file(
    selected_block["state"],
    selected_block["district"],
    selected_block["block"],
)

if gp_boundary_file:
    st.sidebar.success(
        f"GP boundaries loaded: {gp_boundary_file.name}"
    )
else:
    st.sidebar.warning(
        "GP boundary geometry was not found. GP forecast points will still be shown."
    )

# Controls
c1, c2, c3 = st.columns([1.2, 1.2, 2])

with c1:
    variable = st.selectbox(
        "Weather Variable",
        list(VARIABLES.keys()),
        index=0,
    )

dates = sorted(data["target_date"].dropna().unique())
with c2:
    selected_date = st.selectbox(
        "Forecast Day",
        dates,
        format_func=lambda x: pd.Timestamp(x).strftime(
            "%A, %d %b %Y"
        ),
    )

day_data = data[data["target_date"] == selected_date].copy()

# The map only needs one forecast record per GP for the selected day.
day_data = day_data.drop_duplicates(subset=["gp_id"], keep="first").copy()

if day_data.empty:
    st.error("No data for the selected date.")
    st.stop()

horizon = int(day_data["forecast_horizon_day"].iloc[0])

with c3:
    gp_options = ["All GPs"] + sorted(
        day_data["display_name"].astype(str).unique().tolist()
    )
    selected_gp_name = st.selectbox("Focus GP", gp_options)

selected_gp_id = None
if selected_gp_name != "All GPs":
    match = day_data[day_data["display_name"].astype(str) == selected_gp_name]
    if not match.empty:
        selected_gp_id = str(match.iloc[0]["gp_id"])

# Header
state = selected_block["state"]
district = selected_block["district"]
block = selected_block["block"]

st.markdown(
    f"## {safe_label(block)} Block, {safe_label(district)} "
    f"({safe_label(state)})"
)
st.caption(
    f"{len(gps)} Gram Panchayats • D{horizon} • "
    f"{pd.Timestamp(selected_date).strftime('%d %b %Y')} • "
    f"Stage-2 GP spatial correction"
)

# KPI cards
cfg = VARIABLES[variable]
mean_v = day_data[cfg["forecast"]].mean()
min_v = day_data[cfg["forecast"]].min()
max_v = day_data[cfg["forecast"]].max()

k1, k2, k3, k4 = st.columns(4)
k1.metric(f"{cfg['icon']} Mean {variable}", f"{mean_v:.2f} {cfg['unit']}")
k2.metric("Minimum", f"{min_v:.2f} {cfg['unit']}")
k3.metric("Maximum", f"{max_v:.2f} {cfg['unit']}")
k4.metric("GPs mapped", f"{len(day_data)}")

# Map + selected GP details
map_col, info_col = st.columns([2.35, 1])

with map_col:
    st.markdown("### GP Forecast Map")
    st.caption(
        "Marker color represents the selected variable. "
        "Click a GP marker for all four weather variables."
    )

    m = build_map(
        day_data,
        variable,
        selected_gp_id=selected_gp_id,
        boundary_file=boundary_file,
        gp_boundary_file=gp_boundary_file,
    )
    st_folium(
        m,
        width=None,
        height=650,
        returned_objects=[],
        key=f"map_{state}_{district}_{block}_{selected_date}_{variable}",
    )

with info_col:
    st.markdown("### Selected GP")

    if selected_gp_id is None:
        st.info("Select a GP from the Focus GP control to see its full forecast.")
    else:
        r = day_data[day_data["gp_id"] == selected_gp_id].iloc[0]

        st.markdown(f"**{r['display_name']}**")
        st.caption(
            f"GP ID: {r['gp_id']}  \n"
            f"Lat: {r['latitude']:.5f}  \n"
            f"Lon: {r['longitude']:.5f}"
        )

        st.metric(
            f"{VARIABLES['Temperature']['icon']} Temperature",
            f"{r['gp_temperature_corrected']:.2f} °C",
        )
        st.metric(
            f"{VARIABLES['Humidity']['icon']} Humidity",
            f"{r['gp_humidity_corrected']:.2f} %",
        )
        st.metric(
            f"{VARIABLES['Precipitation']['icon']} Precipitation",
            f"{r['gp_precipitation_corrected']:.2f} mm",
        )
        st.metric(
            f"{VARIABLES['Wind Speed']['icon']} Wind",
            f"{r['gp_wind_corrected']:.2f} m/s",
        )

# Full 7-day table
st.markdown("---")
st.markdown("### 7-Day Forecast for Selected GP")

if selected_gp_id is not None:
    gp7 = data[data["gp_id"] == selected_gp_id].sort_values("forecast_horizon_day")

    table = gp7[
        [
            "target_date",
            "forecast_horizon_day",
            "gp_temperature_corrected",
            "gp_humidity_corrected",
            "gp_precipitation_corrected",
            "gp_wind_corrected",
        ]
    ].copy()

    table["target_date"] = table["target_date"].dt.strftime("%Y-%m-%d")
    table.columns = [
        "Date",
        "Day",
        "Temperature (°C)",
        "Humidity (%)",
        "Precipitation (mm)",
        "Wind (m/s)",
    ]

    st.dataframe(
        table.round(2),
        use_container_width=True,
        hide_index=True,
    )
else:
    st.info("Choose a Focus GP above to display its complete D1–D7 forecast.")

# Block vs GP comparison
st.markdown("---")
st.markdown(f"### Block Forecast vs GP — D{horizon}")

comparison = pd.DataFrame(
    {
        "Variable": [
            "Temperature (°C)",
            "Humidity (%)",
            "Precipitation (mm)",
            "Wind (m/s)",
        ],
        "Block Forecast": [
            day_data["block_temperature_raw"].iloc[0],
            day_data["block_humidity_raw"].iloc[0],
            day_data["block_precipitation_raw"].iloc[0],
            day_data["block_wind_raw"].iloc[0],
        ],
        "GP Mean": [
            day_data["gp_temperature_corrected"].mean(),
            day_data["gp_humidity_corrected"].mean(),
            day_data["gp_precipitation_corrected"].mean(),
            day_data["gp_wind_corrected"].mean(),
        ],
    }
)

st.dataframe(
    comparison.round(2),
    use_container_width=True,
    hide_index=True,
)

# Raw downloadable data for selected block/day
csv_bytes = day_data.to_csv(index=False).encode("utf-8")
st.download_button(
    "⬇️ Download Selected-Day GP Forecast CSV",
    data=csv_bytes,
    file_name=f"{block}_GP_forecast_D{horizon}_{pd.Timestamp(selected_date).date()}.csv",
    mime="text/csv",
)

st.caption(
    "Scientific note: Stage-2 predictions are corrections toward the "
    "ERA5-Land reference field, not independent GP station-observation accuracy."
)
